nodeLinker: node-modules
npmScopes:
  flash-global66:
    npmRegistryServer: "https://npm.pkg.github.com"
  fortawesome:
    npmRegistryServer: "https://npm.fontawesome.com"
npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GBP_PACKAGE_TOKEN}"
  "https://npm.fontawesome.com":
    npmAuthToken: "${FONT_AWESOME_TOKEN}"
