// prefijo fal
export {
  faTimes,
  faCopy,
  faCalendarAlt,
  faLongArrowRight,
  faArrowLeft,
  faArrowRight,
  faCloudDownloadAlt,
  faAngleDown,
  faClock,
  faMinus,
  faEquals,
  faDivide,
  faExclamation,
  faMoneyBillWave,
  faSync,
  faChevronRight,
  faComment,
  faStore,
  faPencil,
  faTruckFast,
  faWarehouseFull,
  faBriefcase,
  faChartSimple,
  faDownToLine,
} from '@fortawesome/pro-light-svg-icons';
