export const BENEFITS_CARD_MIN_BENEFITS = 3;
export const BENEFITS_CARD_MAX_BENEFITS = 5;
export const BENEFITS_CARD_HEADING_LEVELS = [1, 2, 3, 4, 5, 6] as const;
export const BENEFITS_CARD_DEFAULT_HEADING_LEVEL = 2;
