import type { InjectionKey } from 'vue';

export const IMAGE_NAMES = [
  'alert',
  'at',
  'barrier',
  'bell',
  'bolt',
  'calendar',
  'card',
  'celebration',
  'chat-bubble',
  'check',
  'clock',
  'disconnected-plug',
  'discount',
  'document',
  'dollar-currency',
  'door',
  'email',
  'euro-currency',
  'face-recognition',
  'fingerprint',
  'footsteps',
  'gift-box',
  'global66',
  'globe',
  'headset',
  'id-card-back',
  'id-card-front',
  'information',
  'location-pin',
  'lock',
  'magnifying-glass',
  'otp',
  'paper-airplane',
  'pound-currency',
  'price-tags',
  'prohibited',
  'prohibited-red',
  'refresh',
  'sales',
  'scissors',
  'stairs',
  'user',
  'users',
  'warning-sign',
  'warning-sign-yellow',
  'whatsapp',
  'wrench',
  'people',
  'vault',
  'usdt-usdc',
  'code',
  'wallet',
] as const;

export const IMAGE_SIZES = {
  xs: '44px',
  sm: '64px',
  md: '80px',
  lg: '112px',
  xl: '160px',
  '2xl': '208px',
  '3xl': '260px',
} as const;

export const ILLUSTRATION_EXTENSION = 'webp';

export const IMAGE_BASE_URL_DEFAULT = '/illustrations';

export const imageBaseUrlKey: InjectionKey<string> = Symbol('gImageBaseUrl');
