export const IMAGE_NAMES = [
  'alert',
  'at',
  'barrier',
  'bell',
  'bolt',
  'calendar',
  'card',
  'celebration',
  'chat-bubble',
  'check',
  'clock',
  'disconnected-plug',
  'document',
  'dollar-currency',
  'door',
  'email',
  'euro-currency',
  'face-recognition',
  'fingerprint',
  'footsteps',
  'gift-box',
  'global66',
  'globe',
  'headset',
  'id-card-back',
  'id-card-front',
  'information',
  'location-pin',
  'lock',
  'magnifying-glass',
  'otp',
  'paper-airplane',
  'pound-currency',
  'price-tags',
  'prohibited',
  'prohibited-red',
  'refresh',
  'sales',
  'scissors',
  'stairs',
  'user',
  'warning-sign',
  'warning-sign-yellow',
  'whatsapp',
  'wrench'
] as const;

export const IMAGE_SIZES = {
  'xs': '44px',
  'sm': '64px',
  'md': '80px',
  'lg': '112px',
  'xl': '160px',
  '2xl': '208px',
  '3xl': '260px',
} as const;