#!/usr/bin/env node
// Installs the Font Awesome source packages into an isolated, gitignored
// vendor dir (.fa-vendor) so the workspace install never touches
// npm.fontawesome.com. Only `yarn icon:extract` / `yarn icon:add` need them.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const VENDOR_DIR = join(ROOT, '.fa-vendor');
const VENDOR_MANIFEST = join(VENDOR_DIR, 'package.json');

const FA_PACKAGES = {
  '@awesome.me/kit-3edc55bdad': '^1.0.9',
  '@fortawesome/free-brands-svg-icons': '^6.7.2',
  '@fortawesome/pro-duotone-svg-icons': '^6.7.2',
  '@fortawesome/pro-light-svg-icons': '^6.7.2',
  '@fortawesome/pro-regular-svg-icons': '^6.7.2',
  '@fortawesome/pro-solid-svg-icons': '^6.7.2',
};

const TOKEN_VAR = 'FONT_AWESOME_TOKEN';

function resolveToken() {
  return process.env.FONT_AWESOME_TOKEN || process.env.FONTAWESOME_NPM_AUTH_TOKEN || '';
}

function vendorIsReady() {
  if (!existsSync(join(VENDOR_DIR, 'node_modules'))) return false;
  try {
    const vendorRequire = createRequire(VENDOR_MANIFEST);
    for (const pkg of Object.keys(FA_PACKAGES)) {
      vendorRequire.resolve(`${pkg}/package.json`);
    }
    return true;
  } catch {
    return false;
  }
}

async function manifestMatches() {
  try {
    const current = JSON.parse(await readFile(VENDOR_MANIFEST, 'utf8'));
    return JSON.stringify(current.dependencies) === JSON.stringify(FA_PACKAGES);
  } catch {
    return false;
  }
}

async function writeVendorFiles() {
  await mkdir(VENDOR_DIR, { recursive: true });
  await writeFile(
    VENDOR_MANIFEST,
    JSON.stringify(
      {
        name: 'fa-vendor',
        private: true,
        description: 'Throwaway install target for Font Awesome source packages. Generated by scripts/ensure-fa.mjs — do not commit.',
        dependencies: FA_PACKAGES,
      },
      null,
      2,
    ) + '\n',
    'utf8',
  );
  await writeFile(
    join(VENDOR_DIR, '.npmrc'),
    [
      '@fortawesome:registry=https://npm.fontawesome.com/',
      '@awesome.me:registry=https://npm.fontawesome.com/',
      `//npm.fontawesome.com/:_authToken=\${${TOKEN_VAR}}`,
      '',
    ].join('\n'),
    'utf8',
  );
}

async function main() {
  if ((await manifestMatches()) && vendorIsReady()) {
    console.log('✓ Font Awesome vendor packages already installed (.fa-vendor)');
    return;
  }

  const token = resolveToken();
  if (!token) {
    console.error('✗ Missing Font Awesome auth token.');
    console.error(`  Export ${TOKEN_VAR} with a valid npm.fontawesome.com token and retry:`);
    console.error(`    export ${TOKEN_VAR}=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`);
    console.error('  The token is only needed to add/extract icons — never for building or CI.');
    process.exit(1);
  }

  await writeVendorFiles();

  console.log('▶ Installing Font Awesome source packages into .fa-vendor (one-time, gitignored)\n');
  const result = spawnSync('npm', ['install', '--no-audit', '--no-fund', '--loglevel=error'], {
    cwd: VENDOR_DIR,
    stdio: 'inherit',
    env: { ...process.env, [TOKEN_VAR]: token },
  });
  if (result.status !== 0) {
    console.error('\n✗ npm install failed. Check that your Font Awesome token is valid.');
    process.exit(result.status ?? 1);
  }
  console.log('\n✓ Font Awesome vendor packages ready');
}

main().catch((err) => {
  console.error('\n✗ ensure-fa failed:', err.message);
  process.exit(1);
});
