#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const ICON_SETS_PATH = join(ROOT, 'src/icon-sets.ts');
const LIB_DIR = join(ROOT, 'src/lib');

const CATEGORY_MAP = {
  solid:   { pkg: '@fortawesome/pro-solid-svg-icons',   prefix: 'fas', file: 'fas-solid-pro.ts',   accessor: (m) => m },
  regular: { pkg: '@fortawesome/pro-regular-svg-icons', prefix: 'far', file: 'far-regular-pro.ts', accessor: (m) => m },
  light:   { pkg: '@fortawesome/pro-light-svg-icons',   prefix: 'fal', file: 'fal-light-pro.ts',   accessor: (m) => m },
  duotone: { pkg: '@fortawesome/pro-duotone-svg-icons', prefix: 'fad', file: 'fad-duotone-pro.ts', accessor: (m) => m },
  brands:  { pkg: '@fortawesome/free-brands-svg-icons', prefix: 'fab', file: 'fab-free.ts',        accessor: (m) => m },
  kit:     { pkg: '@awesome.me/kit-3edc55bdad/icons',   prefix: 'fak', file: 'fa-kit.ts',          accessor: (m) => m.fak },
};

function kebabToCamel(name) {
  return name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

export function toExportName(iconName) {
  const camel = kebabToCamel(iconName);
  return 'fa' + camel.charAt(0).toUpperCase() + camel.slice(1);
}

async function parseIconSets() {
  const src = await readFile(ICON_SETS_PATH, 'utf8');
  const sets = {};
  for (const key of Object.keys(CATEGORY_MAP)) {
    const re = new RegExp(`${key}\\s*:\\s*\\[([\\s\\S]*?)\\]\\s*as\\s*const`, 'm');
    const match = src.match(re);
    if (!match) throw new Error(`Cannot find icon-sets[${key}] in ${ICON_SETS_PATH}`);
    const raw = [...match[1].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
    const seen = new Set();
    const deduped = [];
    const duplicates = [];
    for (const name of raw) {
      if (seen.has(name)) duplicates.push(name);
      else { seen.add(name); deduped.push(name); }
    }
    if (duplicates.length > 0) {
      console.warn(`  ⚠ icon-sets[${key}] has duplicates: ${duplicates.join(', ')}`);
    }
    sets[key] = deduped;
  }
  return sets;
}

function serializeIcon(catalogName, exportName, faIcon, isCustomKit) {
  const [w, h, aliases, unicode, path] = faIcon.icon;
  const stringAliases = Array.isArray(aliases)
    ? aliases.filter((a) => typeof a === 'string')
    : [];
  if (faIcon.iconName !== catalogName && !stringAliases.includes(catalogName)) {
    stringAliases.push(catalogName);
  }
  const aliasesJson = JSON.stringify(stringAliases);
  const unicodeJson = JSON.stringify(unicode);
  const pathJson = JSON.stringify(path);
  const cast = isCustomKit ? 'as unknown as IconDefinition' : 'as IconDefinition';
  return `export const ${exportName} = { prefix: '${faIcon.prefix}', iconName: '${faIcon.iconName}', icon: [${w}, ${h}, ${aliasesJson}, ${unicodeJson}, ${pathJson}] } ${cast};`;
}

async function extractCategory(category, { pkg, prefix, file, accessor }, catalog) {
  const mod = require(pkg);
  const lookup = accessor(mod);
  const isCustomKit = category === 'kit';
  const lines = [
    '// AUTO-GENERATED by scripts/extract-icons.mjs — do not edit by hand.',
    `// Source: ${pkg}`,
    `// Prefix: ${prefix}`,
    '// Run `yarn icon:extract` to regenerate. Add icons via `yarn icon:add "<weight> <name>"`.',
    '',
    "import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';",
    '',
  ];
  const missing = [];
  for (const name of catalog) {
    const exportName = toExportName(name);
    const icon = lookup?.[exportName];
    if (!icon || !icon.icon) {
      missing.push(`${name} (expected export ${exportName})`);
      continue;
    }
    lines.push(serializeIcon(name, exportName, icon, isCustomKit));
  }
  if (missing.length > 0) {
    throw new Error(`[${category}] Missing icons in ${pkg}:\n  - ${missing.join('\n  - ')}`);
  }
  const outPath = join(LIB_DIR, file);
  await writeFile(outPath, lines.join('\n') + '\n', 'utf8');
  return { file, count: catalog.length, outPath };
}

async function main() {
  const sets = await parseIconSets();
  console.log('▶ Extracting Font Awesome icons inline from node_modules\n');
  for (const [category, config] of Object.entries(CATEGORY_MAP)) {
    const catalog = sets[category];
    process.stdout.write(`  ${category.padEnd(8)} (${String(catalog.length).padStart(3)} icons) `);
    const result = await extractCategory(category, config, catalog);
    console.log(`→ ${result.file}`);
  }
  console.log('\n✓ Extraction complete. Run `yarn build` to bundle the icon-font package.');
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  main().catch((err) => {
    console.error('\n✗ Extraction failed:', err.message);
    process.exit(1);
  });
}
