name: Deploy Storybook

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GBP_PACKAGE_TOKEN: ${{ secrets.GBP_PACKAGE_TOKEN }}
      FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Verify Yarn configuration
        run: |
          echo "Verificando configuración de Yarn y variables de entorno..."
          yarn config list
          # No imprime los tokens por seguridad
          if [ -z "$GBP_PACKAGE_TOKEN" ]; then echo "⚠️ GBP_PACKAGE_TOKEN no está configurado"; else echo "✓ GBP_PACKAGE_TOKEN configurado"; fi
          if [ -z "$FONT_AWESOME_TOKEN" ]; then echo "⚠️ FONT_AWESOME_TOKEN no está configurado"; else echo "✓ FONT_AWESOME_TOKEN configurado"; fi
      
      - name: Build Storybook
        id: build
        run: yarn build-storybook
        
      - name: Check build output
        run: |
          if [ ! -d "./storybook-static" ]; then
            echo "::error::La carpeta de build no existe"
            exit 1
          fi
      
      - name: Create .nojekyll file
        run: touch ./storybook-static/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          force_orphan: true
          publish_branch: gh-pages
          
      - name: Notify success
        if: success()
        run: echo "✅ Storybook desplegado exitosamente en https://flash-global66.github.io/b2b-ui-framework/"
        
      - name: Notify failure
        if: failure()
        run: echo "❌ Falló el despliegue de Storybook"
