name: Build and Deploy Storybook to Render

on:
  push:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack and Install Yarn 4.7.0
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate

      - name: Verify environment variables
        run: |
          if [ -z "$GBP_PACKAGE_TOKEN" ]; then 
            echo "::error::GBP_PACKAGE_TOKEN no está configurado"
            exit 1
          fi
          if [ -z "$FONT_AWESOME_TOKEN" ]; then 
            echo "::error::FONT_AWESOME_TOKEN no está configurado"
            exit 1
          fi
          echo "✅ Variables de entorno configuradas correctamente"

      - name: Install dependencies
        run: yarn install

      - name: Create building of components
        run: |
          echo "Building packages in specific order"

          ORDERED_COMPONENTS=("form" "icon-font" "button")

          for component in "${ORDERED_COMPONENTS[@]}"; do
            echo "Building @flash-global66/$component"
            yarn build $component
            
            # Verificar si la construcción fue exitosa
            if [ $? -ne 0 ]; then
              echo "Error building $component"
              exit 1
            fi
          done

          echo "Build remaining packages"

          ALL_COMPONENTS=$(find components -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)

          for component in $ALL_COMPONENTS; do
            # Verificar si el componente ya fue construido
            if [[ ! " ${ORDERED_COMPONENTS[@]} " =~ " $component " ]] && [[ ! " ${ORDERED_COMPONENTS[@]} " =~ " g-$component " ]]; then
              echo "Building @flash-global66/$component"
              yarn build $component
            fi
          done

          echo "All components built successfully"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          GBP_PACKAGE_TOKEN: ${{ secrets.GBP_PACKAGE_TOKEN }}
          FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          OWNER_NAME: ${{ github.repository_owner }}
        run: |
          owner=$(echo "$OWNER_NAME" | tr '[:upper:]' '[:lower:]')
          repo_name=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          docker build \
            -f Dockerfile.prod \
            --build-arg GBP_PACKAGE_TOKEN=$GBP_PACKAGE_TOKEN \
            --build-arg FONT_AWESOME_TOKEN=$FONT_AWESOME_TOKEN \
            -t ghcr.io/$owner/$repo_name:develop .
          
          docker push ghcr.io/$owner/$repo_name:develop

  deploy-to-render:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment via Webhook
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST "$DEPLOY_HOOK"
