name: Build and Deploy Storybook to Render

on:
  push:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          GBP_PACKAGE_TOKEN: ${{ secrets.GBP_PACKAGE_TOKEN }}
          FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          OWNER_NAME: ${{ github.repository_owner }}
        run: |
          owner=$(echo "$OWNER_NAME" | tr '[:upper:]' '[:lower:]')
          repo_name=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          docker build \
            -f Dockerfile.prod \
            --build-arg GBP_PACKAGE_TOKEN=$GBP_PACKAGE_TOKEN \
            --build-arg FONT_AWESOME_TOKEN=$FONT_AWESOME_TOKEN \
            -t ghcr.io/$owner/$repo_name:develop .
          
          docker push ghcr.io/$owner/$repo_name:develop

  deploy-to-render:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment via Webhook
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST "$DEPLOY_HOOK"