/** Nombres de logo: kebab-case, sin extensión. Debe coincidir con `assets/logos/{name}.svg` */
export const LOGO_NAMES = [
  'icon-bre-b',
  'icon-global66',
  'icon-global66-b2b',
  'icon-global66-b2b-on-dark',
  'icon-global66-b2c',
  'icon-global66-b2c-on-dark',
  'label-global66',
  'logo-alfin',
  'logo-banbif',
  'logo-bancolombia',
  'logo-bancom',
  'logo-bbva',
  'logo-bcp',
  'logo-bim',
  'logo-caja-huancayo',
  'logo-caja-ica',
  'logo-caja-lima',
  'logo-caja-los-andes',
  'logo-caja-piura',
  'logo-caja-sullana',
  'logo-caja-tacna',
  'logo-caja-trujillo',
  'logo-cce',
  'logo-citibank',
  'logo-cmac-arequipa',
  'logo-compartamos-financiera',
  'logo-cooperativa-abaco',
  'logo-credinka',
  'logo-crediscotia',
  'logo-dale',
  'logo-falabella',
  'logo-financiera-confianza',
  'logo-financiera-efectiva',
  'logo-global66',
  'logo-gnb',
  'logo-horizontal-global66',
  'logo-horizontal-global66-b2b',
  'logo-horizontal-global66-b2b-on-dark',
  'logo-horizontal-global66-on-dark',
  'logo-interbank',
  'logo-ligo',
  'logo-luqea',
  'logo-mastercard',
  'logo-mi-banco',
  'logo-nacion',
  'logo-nequi',
  'logo-pichincha',
  'logo-plin',
  'logo-prexpe',
  'logo-pse',
  'logo-ripley',
  'logo-scotiabank',
  'logo-tarjeta-oh',
  'logo-vertical-global66',
  'logo-vertical-global66-b2b',
  'logo-vertical-global66-b2b-on-dark',
  'logo-vertical-global66-on-dark',
  'logo-visa',
  'logo-yape',
] as const;

/**
 * Convención de nombres:
 * - `icon-{marca}` — isotipo / símbolo
 * - `label-{marca}` — wordmark / texto
 * - `logo-{marca}` — lockup completo (aliados, tarjetas, etc.)
 * - `logo-horizontal-{marca}` / `logo-vertical-{marca}` — variantes Global66
 * - sufijo `-on-dark` — versión para fondos oscuros
 * - sufijo `-b2b` / `-b2c` — segmento Global66
 */
export const LOGO_GROUPS = [
  {
    id: 'global66',
    label: 'Global66',
    names: [
      'icon-global66',
      'icon-global66-b2b',
      'icon-global66-b2b-on-dark',
      'icon-global66-b2c',
      'icon-global66-b2c-on-dark',
      'label-global66',
      'logo-global66',
      'logo-horizontal-global66',
      'logo-horizontal-global66-on-dark',
      'logo-horizontal-global66-b2b',
      'logo-horizontal-global66-b2b-on-dark',
      'logo-vertical-global66',
      'logo-vertical-global66-on-dark',
      'logo-vertical-global66-b2b',
      'logo-vertical-global66-b2b-on-dark',
    ],
  },
  {
    id: 'colombia',
    label: 'Colombia',
    names: ['icon-bre-b', 'logo-bancolombia', 'logo-dale', 'logo-nequi', 'logo-pse'],
  },
  {
    id: 'medios-pago',
    label: 'Medios de pago',
    names: [
      'logo-ligo',
      'logo-mastercard',
      'logo-plin',
      'logo-prexpe',
      'logo-visa',
      'logo-yape',
    ],
  },
  {
    id: 'peru',
    label: 'Perú — bancos y financieras',
    names: [
      'logo-alfin',
      'logo-banbif',
      'logo-bancom',
      'logo-bbva',
      'logo-bcp',
      'logo-bim',
      'logo-caja-huancayo',
      'logo-caja-ica',
      'logo-caja-lima',
      'logo-caja-los-andes',
      'logo-caja-piura',
      'logo-caja-sullana',
      'logo-caja-tacna',
      'logo-caja-trujillo',
      'logo-cce',
      'logo-citibank',
      'logo-cmac-arequipa',
      'logo-compartamos-financiera',
      'logo-cooperativa-abaco',
      'logo-credinka',
      'logo-crediscotia',
      'logo-falabella',
      'logo-financiera-confianza',
      'logo-financiera-efectiva',
      'logo-gnb',
      'logo-interbank',
      'logo-luqea',
      'logo-mi-banco',
      'logo-nacion',
      'logo-pichincha',
      'logo-ripley',
      'logo-scotiabank',
      'logo-tarjeta-oh',
    ],
  },
] as const;

export const LOGO_SIZES = {
  'xs': '12px',
  'sm': '16px',
  'md': '24px',
  'lg': '32px',
} as const;

/** Dimensiones del contenedor en carga/error (ancho extra para que quepa "404") */
export const LOGO_PLACEHOLDER_SIZES = {
  xs: { width: '28px', height: '12px' },
  sm: { width: '34px', height: '16px' },
  md: { width: '40px', height: '24px' },
  lg: { width: '52px', height: '32px' },
} as const;

export const LOGO_FILTERS = {
  none: 'none',
  grayscale: 'grayscale(100%)',
  black: 'brightness(0)',
  white: 'brightness(0) invert(1)',
  sepia: 'sepia(100%)',
  'opacity-50': 'opacity(50%)',
  'high-contrast': 'contrast(200%)',
  invert: 'invert(100%)',
} as const;

export const LOGO_FILTER_OPTIONS = Object.keys(LOGO_FILTERS) as (keyof typeof LOGO_FILTERS)[];

export const LOGO_FILTER_LABELS: Record<keyof typeof LOGO_FILTERS, string> = {
  none: 'Original',
  grayscale: 'Gris',
  black: 'Negro',
  white: 'Blanco',
  sepia: 'Sepia',
  'opacity-50': '50% opacidad',
  'high-contrast': 'Contraste alto',
  invert: 'Invertido',
};
